component integration fixes
shakeelanalytics/global-components pull request #1
Opened 2023-01-11 11:37 UTC by faizan-tenx

2023-01-12 13:08 UTC, shakeelanalytics requested changes

2023-01-12 13:08 UTC, shakeelanalytics commented on src/components/datagrid/index.tsx
> +  if (props?.actionsProps?.secondaryActions) {
if it's possible please convert these actions into a separate file for better readability

2023-01-12 13:08 UTC, shakeelanalytics commented on src/components/datagrid/index.tsx
> +  if (props?.actionsProps?.secondaryActions) {
like columns file

2023-01-12 13:08 UTC, shakeelanalytics commented on src/components/datagrid/index.tsx
> +                color='secondary'
reuse custom button component instead of rewriting the whole button html

2023-01-13 07:24 UTC, faizan-tenx commented on src/components/status-chip/statusChip.tsx
> +      case 'active':
done

2023-01-13 07:25 UTC, faizan-tenx commented on src/components/tables/EnhancedTableToolBar.tsx
>  import _debounce from "lodash/debounce";
its important for us to use this library. otherwise we cant control multiple requests

2023-01-13 07:25 UTC, faizan-tenx commented on src/components/tables/EnhancedTableToolBar.tsx
>  interface Props {
props are converted to the best

2023-01-13 07:26 UTC, faizan-tenx commented on src/components/search-field/searchBar.tsx
> +  handleSearchField: any;
did some changes, but cant simplify more than that.

2023-01-13 07:26 UTC, faizan-tenx commented on src/components/dropdown/index.tsx
> +            <MenuItem
it is incomplete component thats why commented

2023-01-13 07:26 UTC, faizan-tenx commented on src/components/dropdown/index.tsx
> +  value: any;
converted to the best

2023-01-13 07:27 UTC, faizan-tenx commented on src/components/dropdown/index.tsx
> +import _debounce from "lodash/debounce";
done

2023-01-13 07:27 UTC, faizan-tenx commented on src/components/datagrid/index.tsx
> +  if (props?.actionsProps?.secondaryActions) {
cant separate more.

2023-01-13 07:29 UTC, faizan-tenx commented on src/components/datagrid/index.tsx
> +                color='secondary'
cant use that componnet here

2023-01-17 06:56 UTC, merged